### ISSUE TITLE
Use racket-reloadable

### ISSUE THREAD

**Issue by lehitoskin** [Metaxal/rwind#8]
The [racket-reloadable](https://github.com/tonyg/racket-reloadable) library is designed for programs that stay on for long amounts of time like servers or, say, a window manager. It splits up code between *permanent* and *reloadable* parts, which got me thinking about this project, which I think could benefit from using such a library, what with modifying configuration files or even sections of the window manager itself.

**Comment by Metaxal** [comment]
(sorry for the late reply, the last weeks were pretty full)
Thanks for the pointer. Reloading seems to work fine in RWind now, so I'll
probably won't touch it, unless I discover an important problem with it.
I'll keep it in a corner of my mind though.
